# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_id', models.CharField(max_length=256, null=True, unique=True)),
                ('resolution_text', models.TextField(null=True)),
                ('resolution_passed', models.NullBooleanField(default=None)),
                ('date_voting_finished', models.DateField(editable=False, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='unit.OrganisationalUnit')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Abstain'), (4, 'Invalid vote')])),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='resolution.Resolution')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resolutionvote',
            unique_together=set([('voter', 'resolution')]),
        ),
    ]
