# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='resolutionvote',
            options={'ordering': ('vote_time',)},
        ),
        migrations.AddField(
            model_name='resolution',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='render_resolution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolution_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='resolution_id',
            field=models.CharField(blank=True, default=None, editable=False, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='resolutionvote',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='resolution.Resolution'),
        ),
        migrations.AddField(
            model_name='resolutionformat',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='resolution.Resolution'),
        ),
    ]
