version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=resolution_fastly

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - mailhog
    environment:
      - POSTGRES_USER=resolution_fastly
      - USE_DOCKER=yes
      - WERKZEUG_DEBUG_PIN=off
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=resolution_fastly
    entrypoint: []
    command: /bin/true
    volumes:
      - .:/app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

