# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 17:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('short_name', models.CharField(max_length=5)),
                ('votes_required_to_pass', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('owners', models.ManyToManyField(related_name='_organisationalunit_owners_+', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(related_name='_organisationalunit_voters_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
